In [13]:
# Numpy Arrays

import numpy as np

In [15]:
# Basic array 
arr=np.array([1,2,3,4])

In [17]:
arr

array([1, 2, 3, 4])

In [27]:
a=[1,2,3,4.4]

In [29]:
a


[1, 2, 3, 4.4]

In [31]:
np.array(a)

array([1. , 2. , 3. , 4.4])

In [33]:
l=[[1,2,3],[4,5,6],[7,8,9]]

In [35]:
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [37]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr=np.arange(1,11)

In [43]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr=np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [55]:
arr=np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [63]:
arr=np.linspace(1,5,3)
arr


array([1., 3., 5.])

In [65]:
np.random.rand(5)

array([0.56715141, 0.29962618, 0.47548918, 0.55638491, 0.37961358])

In [67]:
np.random.rand(10)

array([0.89481486, 0.51446676, 0.83264518, 0.88852613, 0.87006546,
       0.33129986, 0.79594564, 0.57620667, 0.32691518, 0.65393444])

In [73]:
np.random.randint(10,20,10)

array([15, 18, 10, 10, 11, 12, 17, 18, 10, 17])

In [ ]:

#Array Attributes 

In [79]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
arr.shape  #rows , cols

(3, 3)

In [85]:
arr.size

9

In [87]:
arr.dtype

dtype('int32')

In [ ]:
#Array Methods

In [89]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
arr.min()

1

In [93]:
arr.max()

9

In [95]:
arr.sum()

45

In [107]:
np.sum(arr,axis=1)   # rows wise


array([ 6, 15, 24])

In [103]:
np.sum(arr,axis=0)   # cols wise

array([12, 15, 18])

In [109]:
arr.mean()

5.0

In [111]:
arr.std()

2.581988897471611

In [113]:
arr.argmax() #argumnet max it mean max element index

8

In [115]:
arr.argmin()  #argumnet min it mean max element index

0

In [ ]:
#Reshaping and Resizing

In [119]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [121]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [123]:
arr=arr.reshape(6,5)   #resize

In [125]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
#Numpy Indexing And Slicing Of Vectors

In [129]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [131]:
arr[6]

17

In [133]:
arr_slice=arr[1:5]  # slicing

array([12, 13, 14, 15])

In [ ]:
#Numpy Indexing and slicing of Matrix

In [135]:
arr=np.arange(1,31).reshape(6,5)

In [137]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [151]:
arr[5,4]

30

In [155]:
slice=arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [159]:
arr[3:6,3:6]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [165]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [ ]:
#Boolean Indexing 

In [175]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [183]:
bool_index=arr %2==0
bool_index

array([ True,  True,  True,  True,  True])

In [185]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])

In [ ]:
#Array Operations

In [187]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [191]:
arr=a1+a2 # array size should be same
arr

array([ 7,  9, 11, 13, 15])

In [193]:
a1-a2

array([-5, -5, -5, -5, -5])

In [195]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [197]:
a2/a2

array([1., 1., 1., 1., 1.])

In [199]:
a1//a2

array([0, 0, 0, 0, 0])

In [ ]:
#BroadCasting

In [201]:
l=[10,20,30,40]
arr=np.array(l)


In [203]:
arr+10

array([20, 30, 40, 50])

In [205]:
#Deep and Shallow copy

a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [211]:
slice=a[:5]
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [215]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [217]:
a[4:6]*10
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [219]:
a
b=a


In [223]:
b[0]=99

In [225]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [227]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
# Matrix operations

In [233]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [235]:
A

array([[1, 2],
       [3, 4]])

In [237]:
B

array([[5, 6],
       [7, 8]])

In [239]:
A*B

array([[ 5, 12],
       [21, 32]])

In [241]:
A @ B

array([[19, 22],
       [43, 50]])

In [243]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [245]:
A

array([[1, 2],
       [3, 4]])

In [251]:
B

array([[5, 6],
       [7, 8]])

In [247]:
A.T

array([[1, 3],
       [2, 4]])

In [249]:
B.T

array([[5, 7],
       [6, 8]])

In [ ]:
#Advance ARRAY manipulation
# Stacking Array

In [265]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [269]:
np.vstack((a,b))  # vertcial stack

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [271]:
np.hstack((a,b))  #horizontal stack

array([1, 2, 3, 4, 5, 6, 7, 8])

In [273]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
#Splitting Array

In [276]:
c=np.arange(16).reshape(4,4)

In [278]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [280]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [286]:
a=np.vsplit(c,4)

In [288]:
a

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [290]:
#Questions

In [ ]:
#1.Valid Sudoku

In [292]:
s= np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],    # sum of  individual rows and cols is equal to 45
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [310]:
d=np.sum(s[0:3,0:3])
d

45

In [300]:
b=np.sum(s,axis=1)
b==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [302]:
for i in b:
    if i!=45:
        print("sudoku is not valid")
        break
else:
    print("for rows it is valid")

for rows it is valid


In [304]:
c=np.sum(s,axis=0)

In [306]:
c

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [308]:
for i in c:
    if i!=45:
        print("sudoku is not valid")
        break
else:
    print("for rows it is valid")

for rows it is valid


In [312]:
e=np.sum(s[0:3,6:9])
e

45

In [318]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n=s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [ ]:
# General Questions

In [423]:
#columns : [age ,  math marks,science marks]
data=np.array([
               [18,85,78], #Student 1
              [19,92,88],  #Student 2
               [17,76,95], #Student 3
               [18,65,70], #Student 4
               [20,90,85]  #Student 5
              ])

In [425]:
#Get the shape of the matrix

data.shape

(5, 3)

In [427]:
#find the avg age of student
np.mean(data[:,0])

18.4

In [429]:
#extract Math marks of all students

In [431]:
data[:,1:2]

array([[85],
       [92],
       [76],
       [65],
       [90]])

In [433]:
#find the highest Science marks
np.max(data[:,2])

95

In [435]:
#Get them details of the student who  scored mpore than 90 in math
data[data[:,1]>90]

array([[19, 92, 88]])

In [437]:
math=data[:,1:2]
math

array([[85],
       [92],
       [76],
       [65],
       [90]])

In [439]:
for i in range(len(math)):
    if math[i] > 90:
        print(math[i])

[92]


In [441]:
#Increae the math marks of all students by 5
data[:, 1] += 5

In [443]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [445]:
#find how many students are younger than 19 
len(data[data[:,0]<19])

3

In [447]:
#calculate the avg  marks in each subject (column-wise mean)
np.mean(data[:,1:],axis=0)


array([86.6, 83.2])

In [449]:
#get data of student who scored at least 80 in both subjects
data[(data[:,1] >=80) & (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [451]:
#replace all science marks <75 with 0

data[:,2][data[:,2]<75]=0

In [453]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])